version: '3.8'

services:
  grpc-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - ./backend:/app
    working_dir: /app

  grpc-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    depends_on:
      - grpc-backend

  envoy-proxy:
    image: envoyproxy/envoy:v1.22.0
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - grpc-backend